"""Add created_at, updated_at

Revision ID: 8936c4d59282
Revises: aa8a0d11e984
Create Date: 2025-06-21 20:00:10.946443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8936c4d59282"
down_revision: Union[str, Sequence[str], None] = "aa8a0d11e984"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("contacts", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "updated_at")
    op.drop_column("contacts", "created_at")
    # ### end Alembic commands ###
